import type { GtdSettings } from "../settings";

export const TEST_SETTINGS: GtdSettings = {
  agentDelegationWebhookUrl: "",
  dailyPlanParent: "[[Plans, Priorities]]",
  dailyReviewNotify: true,
  dailyReviewStaleDays: 2,
  delegateTargetTags: ["people", "agents"],
  hideProcessButton: false,
  hotkeyDelegate: "d",
  hotkeyDone: "e",
  hotkeyProject: "p",
  hotkeySomeday: "s",
  hotkeyWatch: "w",
  inboxPage: "Triage",
  locale: "en",
  reviewItemMode: "list",
  showTooltips: true,
  staleDays: 14,
  tagDelegated: "delegated",
  tagNextAction: "up",
  tagSomeday: "someday",
  tagWaitingFor: "watch",
  topGoalAttr: "Top Goal",
  triggerListPage: "Trigger List",
  weeklyReviewDay: 0,
  weeklyReviewNotify: true,
  weeklyReviewTime: "09:00",
};
